export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_LOADING = 'SIGN_UP_LOADING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const GET_CART_LOADING = 'GET_CART_LOADING';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_ERORR = 'GET_CART_ERORR';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_CART = 'REMOVE_CART';

// export const FETCH_CART_LOADING = 'FETCH_CART_LOADING';
// export const FETCH_CART_ERROR = 'FETCH_CART_ERROR';
// export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'

export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';
export const GET_PRODUCT_SUCCESS= 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';
